---
packageExtensions:
  '@babel/plugin-transform-react-jsx@*':
    dependencies:
      '@babel/core': '*'
  '@babel/preset-env@*':
    dependencies:
      '@babel/core': '*'
  '@joshwooding/vite-plugin-react-docgen-typescript@*':
    dependencies:
      typescript: '*'
  '@mdx-js/react@*':
    dependencies:
      react: '*'
  '@storybook/addon-docs@*':
    dependencies:
      '@storybook/vue3': '*'
  '@storybook/core-client@*':
    dependencies:
      webpack: '*'
  '@storybook/core-common@*':
    dependencies:
      react: '*'
      react-dom: '*'
  '@storybook/core@*':
    dependencies:
      webpack: '*'
  '@storybook/source-loader@*':
    dependencies:
      react: '*'
      react-dom: '*'
  '@storybook/store@*':
    dependencies:
      react: '*'
      react-dom: '*'
  '@storybook/vue3@*':
    dependencies:
      '@babel/core': '*'
      '@vue/compiler-sfc': '*'
      babel-loader: '*'
      vue: '*'
  '@vue/test-utils@*':
    dependencies:
      '@vue/compiler-dom': '*'
  '@vue/vue3-jest@*':
    dependencies:
      '@vue/compiler-sfc': '*'
  babel-loader@*:
    dependencies:
      '@babel/core': '*'
      webpack: '*'
  debug@*:
    dependencies:
      supports-color: '*'
  jscodeshift@*:
    dependencies:
      '@babel/preset-env': '*'
  storybook-addon-pseudo-states@*:
    dependencies:
      '@storybook/addons': '*'
      '@storybook/api': '*'
      '@storybook/components': '*'
      '@storybook/core-events': '*'
      '@storybook/theming': '*'
  stylelint-high-performance-animation@*:
    dependencies:
      postcss-value-parser: '*'
  stylelint@*:
    dependencies:
      postcss-html: '*'
  ts-loader@*:
    dependencies:
      typescript: '*'
  typedoc@*:
    dependencies:
      typedoc-plugin-markdown: '*'
  vue-inbrowser-compiler-utils@*:
    dependencies:
      vue: '*'
plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: '@yarnpkg/plugin-workspace-tools'
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: '@yarnpkg/plugin-typescript'
yarnPath: .yarn/releases/yarn-3.2.0.cjs